import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from './theme';

export const sharedStyles = StyleSheet.create({
  safe:             { flex: 1, backgroundColor: colors.bg, paddingTop: 60 },
  container:        { padding: spacing.lg, gap: spacing.md },
  containerWide:    { maxWidth: 1200, alignSelf: 'center', width: '100%' },
  brand:            { fontSize: 14, letterSpacing: 2, color: colors.textMuted, fontWeight: '600', marginBottom: spacing.sm },
  row:              { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  wideLayout:       { flexDirection: 'row', gap: spacing.lg, alignItems: 'flex-start' },
  wideLeft:         { width: 260, gap: spacing.md },
  wideRight:        { flex: 1, gap: spacing.md },
  button:           { backgroundColor: colors.orange, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderRadius: radius.md },
  buttonSecondary:  { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  buttonDisabled:   { opacity: 0.6 },
  buttonText:       { color: '#fff', fontWeight: '600' },
  smallButton:      { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card },
  smallButtonText:  { color: colors.text, fontWeight: '500' },
  card:             { backgroundColor: colors.card, padding: spacing.lg, borderRadius: radius.lg },
  cardTitle:        { fontSize: 18, fontWeight: '600', color: colors.text },
  cardMeta:         { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  deviceHeader:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.card, padding: spacing.lg, borderRadius: radius.lg },
  tabs:             { flexDirection: 'row', gap: spacing.sm },
  tab:              { flex: 1, paddingVertical: spacing.sm, borderRadius: radius.md, backgroundColor: colors.card, alignItems: 'center' },
  tabActive:        { backgroundColor: colors.orange },
  tabText:          { color: colors.textMuted, fontWeight: '600' },
  tabTextActive:    { color: '#fff' },
  section:          { backgroundColor: colors.card, padding: spacing.lg, borderRadius: radius.lg, gap: spacing.md },
  sectionTitle:     { fontSize: 11, letterSpacing: 1, color: colors.textMuted, fontWeight: '600' },
  grid:             { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  metric:           { minWidth: '45%', flexGrow: 1 },
  metricLabel:      { fontSize: 12, color: colors.textMuted },
  metricValue:      { fontSize: 28, fontVariant: ['tabular-nums'], color: colors.text, fontWeight: '600' },
  metricUnit:       { fontSize: 14, color: colors.textMuted, fontWeight: '400' },
  historyRow:       { flexDirection: 'row', gap: spacing.md, paddingVertical: spacing.xs, borderBottomWidth: 1, borderBottomColor: colors.border },
  historyTime:      { fontSize: 12, color: colors.textMuted, width: 70 },
  historyValue:     { fontSize: 12, color: colors.text, flex: 1 },
  progressTrack:    { height: 4, backgroundColor: colors.border, borderRadius: 2 },
  progressFill:     { height: 4, backgroundColor: colors.orange, borderRadius: 2 },
  warningBanner:    { backgroundColor: '#FFF9E6', borderRadius: radius.sm, padding: spacing.md, borderLeftWidth: 3, borderLeftColor: '#FFCC00' },
  warningText:      { fontSize: 12, color: '#7A5F00' },
  muted:            { color: colors.textMuted },
  error:            { color: '#FF3B30' },
  liveBadge:        { paddingHorizontal: spacing.sm, paddingVertical: 2, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.good },
  liveBadgeText:    { color: colors.good, fontSize: 10, fontWeight: '700' },
});
